FROM node:20-alpine

WORKDIR /app

# Instalar o NestJS CLI globalmente
RUN npm install -g @nestjs/cli

# Copiar arquivos de dependência
COPY package*.json ./

# Instalar dependências
RUN npm install

# Copiar o restante do código
COPY . .

# Gera o cliente Prisma
RUN npx prisma generate

# Expor a porta da aplicação
EXPOSE 3000

# Rodar o serviço em modo de desenvolvimento
CMD ["npm", "run", "start:dev"]
